package com.mckcieply.datemate.ui.home

class GiftIdeas {
    private val giftIdeas = arrayOf(
        "Gift card to a favorite store",
        "Bath set",
        "Power bank",
        "Scented candle",
        "Personalized mug",
        "Tea set",
        "Coffee set",
        "Bluetooth speaker",
        "Notebook or planner",
        "Microfiber blanket",
        "Cosmetics set",
        "Bestselling book",
        "Puzzle",
        "Thermal mug",
        "World spices set",
        "Board game",
        "Tool kit",
        "Phone case",
        "Folding umbrella",
        "Wallet",
        "Elegant pen",
        "Funny patterned socks",
        "Desk organizer",
        "Water filter bottle",
        "Sushi making kit",
        "Mini herb garden",
        "LED night lamp",
        "Fondue set",
        "Soy candle set",
        "Key tracker",
        "Manicure set",
        "Wine set",
        "Personalized pillow",
        "Kitchen gadget (e.g. avocado slicer)",
        "Cocktail making kit",
        "Card game",
        "Fluffy hot water bottle",
        "Creative set (e.g. drawing kit)",
        "Laptop stand",
        "Memory box",
        "Photo calendar",
        "Phone stand",
        "International candy box",
        "Magazine subscription",
        "Car air fresheners",
        "Cinema voucher",
        "3D puzzle",
        "Indoor bonsai tree",
        "Couples mug set",
        "Online course (e.g. language learning)",
        "Custom star map (night sky on a special date)",
        "Portable mini projector",
        "Personalized Spotify plaque",
        "Custom recipe book",
        "Plant growing lamp for indoor gardening",
        "Bluetooth sleep mask with speakers",
        "Eco-friendly zero waste starter kit",
        "Customized comic book cover",
        "Color-changing smart light bulbs",
        "Personalized leather keychain",
        "Scratch-off world map",
        "Indoor fire pit or tabletop fireplace",
        "Subscription box (e.g. snacks, books, self-care)",
        "Pet photo portrait (for pet lovers)",
        "Artisanal jam and spread set",
        "Personalized name necklace",
        "DIY pottery kit",
        "Monthly date night idea box",
        "Mini massage gun",
        "Inspirational quote jar",
        "Indoor hanging terrarium",
        "Custom phone stand with photo",
        "Embroidery starter kit",
        "Handmade ceramic mug",
        "Digital detox challenge kit",
        "Customized puzzle with a photo",
        "Reusable notebook with erasable pen",
        "Name-a-star certificate",
        "Portable espresso maker",
        "Mood light alarm clock",
        "Mini zen garden",
        "Mindfulness card deck",
        "Personalized calendar with custom dates",
        "Coloring book for adults",
        "Cooking class gift voucher",
        "Tabletop ring toss game",
        "Insulated wine tumbler",
        "DIY candle-making kit",
        "Luxury hot chocolate set",
        "Himalayan salt lamp",
        "Solar-powered gadget (e.g. charger, light)",
        "Magnetic hourglass timer",
        "Personalized luggage tag",
        "Indoor mini water fountain",
        "Sleep aid sound machine",
        "Handwritten letter service (for long-distance)",
        "Magnetic poetry kit",
        "Origami paper set with guide",
        "Voice-controlled smart assistant",
        "Mug warmer for desk"
    )

    fun getRandomGiftIdea(): String {
        return giftIdeas.random()
    }
}